### PR TITLE
Added Extensions NV_DX_interop(2)

### PR DESCRIPTION
**Pull request by LittleFox94**
Using NV_DX_interop can make the WPF GL-Control a lot faster
because there is no need to copy the Framebuffer to system ram,
converting it's pixel format and then copying it back to graphics
ram.

I can provide a working example if needed :)

### CODE REVIEW

**Comment by LittleFox94** [comment]
Are you still interested in this?
I could re-create the repository and resolve the conflict Github is reporting.

**Comment by dwmkerr** [comment]
Hi Moritz,

Sorry for the late reply, yes indeed I am still interested, if you can
create a PR which is ready to merge then I'll start the process of getting
it into the codebase!

Thanks,

Dave

**Comment by LittleFox94** [comment]
Just a quick status update: I have a working version at home, will test it for performance and come back here with a push. This will probably result in a new pull-request, as the original repo has been deleted a while ago.
I don't start Windows very often, so this may take a while - sorry.

**Comment by LittleFox94** [comment]
Please see the new pull-request.

**Pull request closed without merging**
