### PR TITLE
Replace dynamic invoke

### PR DESCRIPTION
**Pull request by robinsedlaczek**
I was a little confused by the performance project. I think I created it in the past. So I revert this commit. Hopefully it works now. There is no compilation error here.

### CODE REVIEW

**Comment by robinsedlaczek** [comment]
Don't know where this error comes from. I'll continue investigate it...

**Comment by robinsedlaczek** [comment]
I don't know why App Veyor shows this error. When I look into the changes of the OpenGLExtensions.cs in this PR, it looks fine. Please help!

**Comment by dwmkerr** [comment]
Hi Robin,

Let me help - basically you are probably compiling the branch `ReplaceDynamicInvoke`, which I'm guessing compiles without errors, however what AppVeyor is compiling is the result of the merge of `ReplaceDynamicInvoke` into `v/2.4`. So the merge result is different to what you have in your branch and that's probably why you are not seeing the error.

Try checking out `v/2.4` and merging in `ReplaceDynamicInvoke`, that'll probably lead you in the right direction :)

**Comment by robinsedlaczek** [comment]
Thanks a lot Dave! That was the problem. I forgot the merge. Next time I'll remember. :) There is one TODO in the code from me in method 'GetProgramResource'. Can you please have a look?

**Comment by dwmkerr** [comment]
Yes indeed, anything to get me away from battling with the Visual Studio Extensions for a bit :)

**Comment by robinsedlaczek** [comment]
Cool, thx! Sounds tricky with the extensions. I saw the correspondence. Good luck. I'll update the Wiki and then continue with the WPF control.

**Comment by dwmkerr** [comment]
Hi Robin,

PR looks good, with respects to the TODO I think it should just be:

```cs
var lengthParameter = new uint[1];
var parametersParameter = new int[bufSize];

GetDelegateFor<glGetProgramResourceiv>()(program, programInterface, index, propCount, props, bufSize, lengthParameter, parametersParameter);
length = lengthParameter[0];
parameters = parametersParameter;
```

The original implementation was off. I think this is the only change needed then we can merge it

**Comment by robinsedlaczek** [comment]
Great! Comes tomorrow! Ok, now I see the parameters and I am aware of it regarding the next time! :)



Von meinem Windows Phone gesendet
________________________________
Von: Dave Kerr<mailto:notifications@github.com>
Gesendet: ‎22.‎01.‎2015 19:16
An: dwmkerr/sharpgl<mailto:sharpgl@noreply.github.com>
Cc: Robin Sedlaczek<mailto:robin.sedlaczek@live.de>
Betreff: Re: [sharpgl] Replace dynamic invoke (#70)

Hi Robin,

PR looks good, with respects to the TODO I think it should just be:

```cs
var lengthParameter = new uint[1];
var parametersParameter = new int[bufSize];

GetDelegateFor<glGetProgramResourceiv>()(program, programInterface, index, propCount, props, bufSize, lengthParameter, parametersParameter);
length = lengthParameter[0];
parameters = parametersParameter;
```

The original implementation was off. I think this is the only change needed then we can merge it

---

**Comment by robinsedlaczek** [comment]
Hey Dave! Now it should be done!

**Comment by robinsedlaczek** [comment]
Ok, Wiki has been updated with our experiences regarding dynamic invocation of functions.

**Comment by dwmkerr** [comment]
Awesome :)

**Pull request merged**
