### PR TITLE
Replace dynamic invoke

### PR DESCRIPTION
**Pull request by robinsedlaczek**
The PR as discussed below.

### CODE REVIEW

**Comment by robinsedlaczek** [comment]
Hey Dave!

Can you please check if the PR is ok regarding how I handled it here with Git? Hope, I've done it right. Otherwise, give me instructions please! :)

Thanks a lot!

Robin

**Comment by dwmkerr** [comment]
Hi Robin,

Thanks for this. Can you re-target the performance tests to VS2013 and .NET 4.5 (rather than 4.5.1), as VS 2015 is still in CTP and fewer devs have .NET 4.5.1? I'd like to make the 'officially' supported version VS 2013 Community Edition (the latest free version of Visual Studio until 2015 is released at least).

Also, it doesn't compile! Check the build error in the notice above to see, or:

```bash
git checkout -b robinsedlaczek-ReplaceDynamicInvoke v/2.4
git pull https://github.com/robinsedlaczek/sharpgl.git ReplaceDynamicInvoke
```

Looks like `InvokeExtensionFunction` is missing.

**Comment by robinsedlaczek** [comment]
Hey Dave!

Sorry for this poor Quality. Was too late yesterday! I'll correct this asap today!

Robin

Von meinem Windows Phone gesendet
________________________________
Von: Dave Kerr<mailto:notifications@github.com>
Gesendet: ‎21.‎01.‎2015 06:04
An: dwmkerr/sharpgl<mailto:sharpgl@noreply.github.com>
Cc: Robin Sedlaczek<mailto:robin.sedlaczek@live.de>
Betreff: Re: [sharpgl] Replace dynamic invoke (#67)

Hi Robin,

Thanks for this. Can you re-target the performance tests to VS2013 and .NET 4.5 (rather than 4.5.1), as VS 2015 is still in CTP and fewer devs have .NET 4.5.1? I'd like to make the 'officially' supported version VS 2013 Community Edition (the latest free version of Visual Studio until 2015 is released at least).

Also, it doesn't compile! Check the build error in the notice above to see, or:

```bash
git checkout -b robinsedlaczek-ReplaceDynamicInvoke v/2.4
git pull https://github.com/robinsedlaczek/sharpgl.git ReplaceDynamicInvoke
```

Looks like `InvokeExtensionFunction` is missing.

---

**Comment by dwmkerr** [comment]
No worries, it's going to take us a little while to get used to the workflow, don't worry about it!

**Comment by robinsedlaczek** [comment]
Don't compile before push is just not this professional. But thx Dave! :)

Von meinem Windows Phone gesendet
________________________________
Von: Dave Kerr<mailto:notifications@github.com>
Gesendet: ‎21.‎01.‎2015 06:59
An: dwmkerr/sharpgl<mailto:sharpgl@noreply.github.com>
Cc: Robin Sedlaczek<mailto:robin.sedlaczek@live.de>
Betreff: Re: [sharpgl] Replace dynamic invoke (#67)

No worries, it's going to take us a little while to get used to the workflow, don't worry about it!

---

**Pull request closed without merging**
