### PR TITLE
Fixed parsing + added sample that loads obj + mtl + png texture

### PR DESCRIPTION
**Pull request by odalet**
OK, so here is what I did in this PR:

First I wanted to fix all possible errors when parsing floating point numbers, especially for people who do not use '.' as their decimal separator.

So I went searching for all occurences of `.Parse(`, `Convert.To` and also `.Replace` (as the hack consisting in replacing '.' with ',' did not work in the first place - it even messed with US culture parsing for ',' is the thousands separator in such cultures and thus `1.234` was considered to be `1234`)...

All this research led to essentially 3 distinct places where parsing occured:

* A converter in `NETDesignSurface`  where I fixed the parsing logic by explicitely specifying `CultureInfo.InvariantCulture` so that '.' would be the decimal separator.
* Some parsing from textboxes in `VertextControl`. Here, I did not change the logic: becaus it is user-facing UI code, it makes sense to have the user use the decimal separator defined in his regional settings.
* Then the whole OBJ file loader was the huge part. It used many `float.Parse` and `Convert.ToSingle` that needed the extra `CultureInfo.InvariantCulture` argument. Here were also the '.4 replaced by ',' hacks that neeed be removed.

All of this, I ensured was working in two ways:
* Added a few unit tests (because the Converter test needs acces to an internal class, I had to sign the unit tests assemblies and add an `InternalsVisibleTo` attribute to `SharpGL.SceneGraph`).
* Added a sample app (by copy/pasting from other apps and tools) that displays "Ducky.obj" in all its glory with colored materials and a wonderful feather texture... 

While I was at it fixing floating-point parsing, I motivated myself into verifying I could load a more complex OBJ file with materialsx. Hence I hacked a bit `ducky.obj`, added a `mtl` and a `png` file to go with it. Then I needed a gratifying reward, hence the "Ducky Sample". However, because I'm no 3D designer, and barely understand the various light and texture concepts, I suppose the resulting duck  could be far nicer. However, the sample serves its purpose at demonstrating one can now load an OBJ with materials and PNG textures.

This explains all the other little modifications, not strictly related to floating-point parsing. Hope you don't mind!

PS: I also tried to have the OBJ serializer working, however, I think there is a problem in the way vertices are saved (I suppose there are some unwanted duplications), and so I commented back everything after I had fixed in here too floating-point formatting issues.

image

### CODE REVIEW

**Comment by dwmkerr** [comment]
This is *awesome*! I'm checking out the code now, will give it a quick test and look over and then merge and cut a release! Thanks for this @odalet, amazing contribution :)

**Comment by odalet** [comment]
Glad I could help!

**Comment by dwmkerr** [comment]
OK I added a couple of minor changes:

1. Added you to the contributors list
2. Added a screenshot of the ducky sample to the samples section of the readme
3. Moved the ducky sample into the 'winforms samples' folder of the samples solution
4. Updated the `coverage.ps1` script to also collect coverage data from the new test library you wrote

It's merged into master now, cut as release `2.4.4`, just waiting for the build to complete and the new version should be available on Nuget shortly. Thanks so much for your contributions (and adding tests, that makes things so much easier and improves the quality of the codebase) 😄

**Comment by odalet** [comment]
Thanks!

**Pull request merged**
