### PR TITLE
remove useless OpenGL instance in SceneControl.scene

### PR DESCRIPTION
**Pull request by bitzhuwei**
It's about the 'SharpGL.SceneControl' class. In its 'SharpGL.SceneControl.Scene' property there is an OpenGL instance 'gl' created like this: <code>private OpenGL gl = new OpenGL();</code>. (let's call this 'gl' instance 'glA')<br>
Here comes a problem when using the 'SharpGL.SceneControl'. If you use <code>var c = this.sceneControl.Scene.OpenGL.RenderContextProvider;</code>, the <code>c</code> will be <code>null</code>. But actually there is another OpenGL instance(let's call it 'glB') that holds a valid <code>RenderContextProvider</code>. And 'glB' is the one we should have gotten. This 'glB' is instantiated in 'SharpGL.SceneControl''s parent class(SharpGL.OpenGLControl) like this:<code>private readonly OpenGL gl = new OpenGL();</code>. And it has binded to everything that should be. So I think we can force 'glA' pointing to 'glB' by updating the <code>InitializeComponent()</code> method in <code>SharpGL.SceneControl</code> class like this:</p>

<pre><code>
        private void InitializeComponent()
        {
            // 
            // OpenGLCtrl
            // 
            this.Name = "OpenGLCtrl";
            this.scene.OpenGL = this.OpenGL;// force 'glA' pointing to 'glB'
        }
</code></pre>

<p>And also the 'glA''s instatiation should be removed.<br>
Sorry for my english.

### CODE REVIEW

**Comment by AraHaan** [comment]
bruh can you update this fork please. This shit is bitting me badly where I was like WTF why the fuck is the model not rendering on my form even when I call draw on a scene myself.

**Comment by dwmkerr** [comment]
This is a monster PR. OK I'll take it commit by commit and see what I can do

**Comment by dwmkerr** [comment]
@bitzhuwei @AraHaan try `v2.4.5` which should fix this.

**Comment by AraHaan** [comment]
@dwmkerr thanks, so everything from this pr is now part of the library?

**Comment by dwmkerr** [comment]
Yes I believe so we can close this one now @AraHaan !

**Pull request closed without merging**
